// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright 2025-2026 TautCony

namespace ISTgenerAtor;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using JetBrains.Annotations;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class PatchUtilsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext incrementalContext)
    {
        var classExistsProvider = incrementalContext.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { Identifier.Text: "PatchUtils" },
                transform: static (context, t) =>
                    context.SemanticModel.GetDeclaredSymbol(context.Node, t) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null)
            .Collect();

        incrementalContext.RegisterSourceOutput(classExistsProvider, (context, classSymbols) =>
        {
            if (!classSymbols.Any())
            {
                return;
            }

            string[] codes = [
                GenerateBasicMethod(),
                GenerateCoefficientsMethod("GetKnots", [
                    0xff, 0x14, 0x5d, 0xeb, 0x31, 0x0c, 0x82, 0xe2, 0x40, 0x86, 0xfe, 0x22, 0x8a,
                ]),
                GenerateCoefficientsMethod("GetWeights", [
                    0xff, 0xf9, 0x35, 0x7c, 0xd9, 0x1f, 0x7b, 0xab, 0xa0, 0x53, 0x9b, 0xb3, 0x3f,
                ]),
                GenerateCoefficientsMethod("GetSegments", [
                    0xff, 0xc5, 0xdb, 0x77, 0x73, 0x88, 0x17,
                ]),
                GenerateCoefficientsMethod("GetSourceCoefficients", [
                    0xff, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
                    0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x75, 0x74, 0x63, 0x6f, 0x6e, 0x79, 0x2f, 0x49, 0x53, 0x54,
                    0x41, 0x2d, 0x50, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
                ]),
            ];

            context.AddSource(
                "ISTAlter.Core.PatchUtils.g.cs",
                SourceText.From(string.Join("\n", codes), Encoding.UTF8));
        });
    }

    [return: LanguageInjection("csharp")]
    private static string GenerateBasicMethod()
    {
        return @"// <auto-generated/>
namespace ISTAlter.Core;

using System.Text;
using ISTAlter.Utils;
using dnlib.DotNet;

public static partial class PatchUtils
{
    public static byte[] Config
    {
        get
        {
            var p = Recompose();
            return string.Format(Encoding.UTF8.GetString(p, 12, 18), Encoding.UTF8.GetString(p, 0, 12), Encoding.UTF8.GetString(Version)).GetBytes();
        }
    }

    public static byte[] Source => GetSourceCoefficients().GetString(40).GetBytes();

    public static byte[] Recompose()
    {
        var a = GetKnots().Sample(12);
        var b = GetWeights().Sample(12);
        var c = GetSegments().Sample(6);
        var r = new byte[30];
        for (var i = 0; i < 12; i++)
        {
            r[i] = (byte)(a[i] ^ ((i * 0xB1) + 0x5D));
        }

        for (var i = 0; i < 12; i++)
        {
            r[i + 12] = (byte)(b[i] ^ (((i + 12) * 0xB1) + 0x5D));
        }

        for (var i = 0; i < 6; i++)
        {
            r[i + 24] = (byte)(c[i] ^ (((i + 24) * 0xB1) + 0x5D));
        }

        return r;
    }

    public static byte[] Sample(this int[][] coeffs, int length)
    {
        return new StringGenerator(coeffs).Generate().Take(length).Select(v => (byte)v).ToArray();
    }

    public static string GetString(this int[][] coeffs, int length)
    {
        return Encoding.UTF8.GetString(new StringGenerator(coeffs).Generate().Take(length).Where(b => b is >= 0 and <= 0xff).Select(b => (byte)b).ToArray());
    }

    public static byte[] GetBytes(this string s)
    {
        return Encoding.UTF8.GetBytes(s);
    }

    public static void SetPatchedMark(ModuleDefMD module)
    {
        PatchUtils.SetPatchedMarkInner(module);
        PatchUtils.ValidatePatchResult(module);
    }
}
";
    }

    [return: LanguageInjection("csharp")]
    private static string GenerateCoefficientsMethod(string methodName, byte[] data)
    {
        var coefficients = CubicSpline.CalculateCoefficients(data.Skip(1).ToArray());
        var coefficientsString = string.Join(",\n        ", coefficients.Select(c => $"[{string.Join(", ", c)}]"));

        return $@"// <auto-generated/>
public static partial class PatchUtils
{{
    public static int[][] {methodName}() => new int[][]
    {{
        {coefficientsString}
    }};
}}
";
    }
}
